# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tales from the Latent Space
email: edouard@belval.org
description: > # this means to ignore newlines until "baseurl:"
    Software engineering student & machine learning enthusiast, I mostly work with Python, C#, and C/C++. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://belval.org" # the base hostname & protocol for your site
github_username:  Belval

# Build settings
markdown: kramdown
