name: Belval
title: Belval
description: > # this means to ignore newlines until "baseurl:"
  Software engineering student and machine learning enthusiast.
permalink: ':title/'
url: "https://www.belval.org" # the base hostname & protocol for your site, e.g. http://example.com
# Social
#facebook: #Add your Facebook
#twitter: #Add your Twitter
#google-plus: #Add your Google+
github: Belval

# Contact form
email: edouard@belval.org

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
include: [_pages]
